(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function c(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const p="986738-8cdc2a7fdebdc51acfa5607bc",y="https://pixabay.com/api/";let n=1,l="";const g=document.getElementById("search-form"),u=document.querySelector(".gallery"),a=document.querySelector(".load-more");g.addEventListener("submit",b);a.addEventListener("click",f);a.style.display="none";const h=new SimpleLightbox(".gallery a");function b(s){if(s.preventDefault(),l=s.currentTarget.elements.searchQuery.value.trim(),n=1,u.innerHTML="",a.style.display="none",l===""){iziToast.error({title:"Error",message:"Please enter a search query."});return}f()}async function f(){const s=`${y}?key=${p}&q=${encodeURIComponent(l)}&image_type=photo&orientation=horizontal&safesearch=true&page=${n}&per_page=40`;try{const o=await(await fetch(s)).json();if(o.hits.length===0){iziToast.warning({title:"Warning",message:"Sorry, there are no images matching your search query. Please try again."});return}L(o.hits),n+=1,n>Math.ceil(o.totalHits/40)?(a.style.display="none",iziToast.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})):a.style.display="block",n===2&&iziToast.success({title:"Hooray!",message:`We found ${o.totalHits} images.`})}catch(r){console.error("Error fetching images:",r),iziToast.error({title:"Error",message:"Failed to fetch images. Please try again later."})}}function L(s){const r=s.map(({webformatURL:o,largeImageURL:c,tags:e,likes:t,views:i,comments:d,downloads:m})=>`
        <a href="${c}" class="photo-card">
            <img src="${o}" alt="${e}" loading="lazy" />
            <div class="info">
                <p class="info-item"><b>Likes:</b> ${t}</p>
                <p class="info-item"><b>Views:</b> ${i}</p>
                <p class="info-item"><b>Comments:</b> ${d}</p>
                <p class="info-item"><b>Downloads:</b> ${m}</p>
            </div>
        </a>
    `).join("");u.insertAdjacentHTML("beforeend",r),h.refresh()}
//# sourceMappingURL=commonHelpers.js.map
